accessible_charts: true
accessible_tabs: true
analytics:
  ga_prod: ''
breadcrumbs:
  goal:
    - path: /
      label: general.home
  indicator:
    - path: /
      label: general.home
  post:
    - path: /
      label: general.home
    - path: /news/
      label: menu.updates
country:
  name: Vanuatu
  adjective: Vanuatuan
create_goals:
  layout: goal-by-target
  previous_next_links: true
  goals: []
create_indicators:
  layout: indicator
  previous_next_links: true
create_pages:
  - filename: ''
    folder: /
    layout: frontpage-alt
    title: ''
  - filename: ''
    folder: /reporting-status
    layout: reportingstatus
    title: ''
  - filename: indicators.json
    folder: /
    layout: indicator-json
    title: ''
  - filename: ''
    folder: /search
    layout: search
    title: ''
custom_css: []
custom_js:
  - /assets/js/custom.js
data_edit_url: data
data_fields:
  units: ''
  series: ''
date_formats: []
disclaimer:
  phase: ''
  message: ''
email_contacts:
  questions: test@example.com
  suggestions: test@example.com
  functional: test@example.com
environment: staging
footer_language_toggle: none
footer_menu:
  - path: /contact/
    translation_key: menu.contact_us
  - path: 'https://twitter.com/MyTwitterAccount'
    translation_key: general.twitter
  - path: 'https://facebook.com/MyFacebookAccount'
    translation_key: general.facebook
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies
frontpage_cards:
  - title: frontpage.download_all
    content: ''
    include: components/download-all-data.html
    button_label: ''
    button_link: ''
    rule_color: ''
  - title: Vanuatu National Statistics Office
    content: ''
    include: vnso-card.html
    button_label: VNSO Website
    button_link: 'https://vnso.gov.vu'
    rule_color: ''
  - title: 'Department of Strategic Policy, Planning & Aid Coordination'
    content: ''
    include: dsppac-card.html
    button_label: DSPPAC Website
    button_link: 'https://dsppac.gov.vu/'
    rule_color: ''
frontpage_goals_grid:
  title: Our data for National Sustainable Development Plan indicators
  description: >-
    Click on each goal for our National Sustainable Development Plan indicator
    data.
frontpage_heading: ''
frontpage_instructions: ''
frontpage_introduction_banner:
  title: frontpage.nsdp_title
  description: frontpage.nsdp_description
goal_image_base: /vnso-nsdp-platform/assets/img/goals
goal_image_extension: jpg
goals_page:
  title: ''
  description: ''
graph_color_headline: '#004466'
graph_color_headline_high_contrast: '#55a6e5'
graph_color_set: accessible
graph_color_list: []
graph_color_number: 0
header:
  include: header-menu-left-aligned.html
header_language_toggle: dropdown
hide_empty_metadata: true
indicator_config_form:
  enabled: true
  dropdowns: []
  repository_link: >-
    https://github.com/Vanuatu-National-Statistics-Office/vnso-nsdp-platform/tree/develop/indicators
  translation_link: ''
indicator_data_form:
  enabled: true
  repository_link: >-
    https://github.com/Vanuatu-National-Statistics-Office/vnso-nsdp-platform/tree/develop/data
indicator_metadata_form:
  enabled: true
  dropdowns: []
  repository_link: >-
    https://github.com/Vanuatu-National-Statistics-Office/vnso-nsdp-platform/tree/develop/meta
  translation_link: ''
  language: ''
  scopes:
    - national
    - global
    - source_1
    - source_2
    - source_3
  exclude_fields:
    - PillarCode
    - PillarDescription
    - GoalId
    - GoalDescription
    - PolicyObjectiveId
    - PolicyObjectiveDescription
    - IndicatorId
    - IndicatorDescription
  translated: true
languages:
  - en
  - bi
  - fr
languages_public: []
logos:
  - language: ''
    src: assets/img/logo tittle.PNG
    alt: National Development Goals 2030
map_layers:
  - subfolder: area-councils
    label: ''
    min_zoom: 0
    max_zoom: 20
    staticBorders: false
map_options:
  minZoom: 5
  maxZoom: 10
  tileURL: ''
  tileOptions:
    id: ''
    accessToken: ''
    attribution: ''
  colorRange: chroma.brewer.BuGn
  noValueColor: '#f0f0f0'
  styleNormal:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#888888'
    dashArray: ''
  styleHighlighted:
    weight: 1
    opacity: 1
    fillOpacity: 0.7
    color: '#111111'
    dashArray: ''
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: '#172d44'
    dashArray: '5,5'
menu:
  - path: /reporting-status/
    translation_key: Evaluation
    dropdown:
      - path: /reporting-status/
        translation_key: Data availability
      - path: /indicator-overview/
        translation_key: Indicator overview
      - path: /methodology/
        translation_key: Methodology
  - path: /about/
    translation_key: About us
    dropdown:
      - path: /about/
        translation_key: NSPD Online Platform
      - path: /technical-advice/
        translation_key: Technical advice
  - path: /2030-agenda/
    translation_key: Useful information
    dropdown:
      - path: /2030-agenda/
        translation_key: 2030 agenda
      - path: /publications/
        translation_key: Publications
  - path: /government-financial-statistics/
    translation_key: Government financial statistics
    dropdown: []
  - path: /natural-disasters/
    translation_key: Disaster statistics
    dropdown: []
  - path: /area-council-profiles/
    translation_key: Area council profiles
    dropdown: []
metadata_edit_url: metadata
metadata_tabs:
  - scope: national
    title: indicator.national_metadata
    description: indicator.national_metadata_blurb
  - scope: sources
    title: indicator.sources
    description: ''
news:
  category_links: false
non_global_metadata: indicator.national_metadata
remote_data_prefix: _build
reporting_status:
  title: ''
  description: ''
  disaggregation_tabs: false
search_index_boost: []
search_index_extra_fields: []
series_toggle: true
sharethis_property: ''
site_config_form:
  enabled: true
  dropdowns: []
  repository_link: >-
    https://github.com/Vanuatu-National-Statistics-Office/vnso-nsdp-platform/tree/develop/www/_data
  translation_link: ''
validate_indicator_config: false
validate_site_config: false
